apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
    release: kube-prometheus-stack
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
      smtp_from: '${EMAIL}'
      smtp_auth_username: '${SMTP_USERNAME}'
      smtp_auth_password: '${SMTP_PASSWORD}'
      smtp_require_tls: true

    route:
      receiver: 'email-notifications'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: '${EMAIL}'
        send_resolved: true